import { useState } from 'react';
import { usecaseDetails } from '../data/usecaseDetails';
import { MdArrowOutward } from "react-icons/md";

export default function UseCaseStory({ item }) {
 const d=usecaseDetails[item.slug];
 const [stage,setStage]=useState(0);
 return <>
  <nav className="uc-local-nav section" aria-label="On this page"><a href="#example">Example</a><a href="#problems">The problem</a><a href="#capabilities">With memory</a><a href="#workflow">Workflow</a><a href="#questions">Questions</a></nav>
  <section className="uc-story-section section" id="example">
   <div className="uc-story-heading"><span className="eyebrow">{item.planned?'A PROPOSED SCENARIO':'MEMORY IN PRACTICE'}</span><h2>{d.title}</h2><p>{d.intro}</p></div>
   <div className="uc-scenario">
    <div className="uc-scenario-top"><span className="uc-example-label">EXAMPLE WORKFLOW</span><span>{item.name}</span></div>
    <div className="uc-scenario-tabs" role="tablist" aria-label="Explore the memory workflow">{['The request','Relevant memory','The next response'].map((label,i)=><button key={label} id={'scenario-tab-'+i} role="tab" aria-selected={stage===i} aria-controls="scenario-panel" tabIndex={stage===i?0:-1} onClick={()=>setStage(i)} onKeyDown={e=>{if(['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?2:(i+(e.key==='ArrowRight'?1:2))%3;setStage(next);document.getElementById('scenario-tab-'+next)?.focus()}}}><span>0{i+1}</span>{label}</button>)}</div>
    <div className="uc-scenario-body" id="scenario-panel" role="tabpanel" aria-labelledby={'scenario-tab-'+stage} tabIndex={0}>
     <div className="uc-conversation"><span className="uc-example-label">{stage===2?'RESPONSE WITH CONTEXT':'USER REQUEST'}</span><p key={stage}>{stage===2?d.response:d.prompt}</p><div className="uc-conversation-status"><img src="/memory/lighthouse-mark.svg" alt="" width="22" height="26"/><span>{stage===0?'Start with the question.':stage===1?'Recall the context behind it.':'Carry the reasoning forward.'}</span></div></div>
     <div className={'uc-example-memories '+(stage>0?'uc-memory-recalled':'')}><span className="uc-example-label">{stage===0?'WHAT THE WORKFLOW CAN REMEMBER':'RELEVANT RECORDS'}</span>{d.memories.map(([title,body],i)=><article key={title}><span className="uc-memory-index">0{i+1}</span><div><h3>{title}</h3><p>{body}</p></div></article>)}</div>
    </div>
    <div className="uc-scenario-bottom"><span>{item.planned?'Proposed behaviour from the whitepaper.':'Example inputs and responses for this workflow.'}</span><button onClick={()=>setStage((stage+1)%3)}>{stage===2?'Start again':'Continue'} <span aria-hidden="true">→</span></button></div>
   </div>
  </section>
  <section className="uc-story-section section" id="problems"><div className="uc-story-heading"><span className="eyebrow">THE PROBLEM</span><h2>When the context<br/><span className="shine">doesn’t carry forward.</span></h2></div><div className="uc-problem-grid">{d.problems.map(([title,body],i)=><article key={title}><span className="uc-number">0{i+1}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>
  <section className="uc-story-section section" id="capabilities"><div className="uc-story-heading"><span className="eyebrow">{item.planned?'THE PROPOSED MEMORY FOUNDATION':'WHAT MEMORY MAKES POSSIBLE'}</span><h2>Keep what matters.<br/><span className="shine">Build on what came before.</span></h2></div><div className="uc-feature-grid">{d.features.map(([title,body,label,records],i)=><article key={title}><div className="uc-feature-top"><span className="uc-number">0{i+1}</span><span>{label}</span></div><h3>{title}</h3><p>{body}</p><div className="uc-feature-records">{records.map((r,j)=><div key={r}><span aria-hidden="true">{String(j+1).padStart(2,'0')}</span>{r}</div>)}</div></article>)}</div></section>
  <section className="uc-story-section section" id="workflow"><div className="uc-story-heading"><span className="eyebrow">{item.planned?'PROPOSED WORKFLOW':'THE WORKFLOW'}</span><h2>From a new observation<br/><span className="shine">to lasting context.</span></h2></div><div className="uc-long-workflow">{d.workflow.map(([title,body],i)=><article key={title}><span className="uc-step-count">0{i+1}</span><h3>{title}</h3><p>{body}</p></article>)}</div><p className="uc-detail-note">{item.note}</p></section>
  <section className="uc-build-section section"><div><span className="eyebrow">DESIGN YOUR INTEGRATION</span><h2>A memory layer.<br/><span className="shine">Your application’s logic.</span></h2><p>{item.planned?'Use the proposed architecture to scope a reference integration for your hardware and operating environment.':'Connect the memory runtime to the moments your application needs to write, recall and review context.'}</p><a className="text-link" href={item.planned?'/whitepaper.pdf':'https://docs.lighthouse.storage/memory/intro'}>{item.planned?'Read the architecture':'Explore memory documentation'} <MdArrowOutward /></a></div><div className="uc-build-checks">{d.build.map((text,i)=><div key={text}><span>0{i+1}</span><p>{text}</p></div>)}</div></section>
  <section className="uc-story-section section" id="questions"><div className="uc-story-heading"><span className="eyebrow">COMMON QUESTIONS</span><h2>Before you build.</h2></div><div className="uc-faq">{d.faqs.map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></section>
  <section className="uc-resources section"><span className="eyebrow">EXPLORE THE FOUNDATION</span><div><a href="/whitepaper.pdf" target="_blank" rel="noopener"><span>01 / WHITEPAPER</span><h3>The brain for agentic and physical AI</h3><p>Memory architecture, recovery, scope and roadmap.</p><b aria-hidden="true">↗</b></a><a href="https://docs.lighthouse.storage/"><span>02 / DOCUMENTATION</span><h3>Build with Lighthouse</h3><p>Explore the platform and integration documentation.</p><b aria-hidden="true">↗</b></a></div></section>
  <section className="uc-related section"><span className="eyebrow">OTHER WAYS TO USE MEMORY</span><div>{Object.entries(usecaseDetails).filter(([slug])=>slug!==item.slug).map(([slug,info])=><a key={slug} href={'/use-cases/'+slug}><span>{({'trading-agents':'Trading agents','prediction-markets':'Prediction markets','tokenised-assets':'Tokenised assets','physical-ai':'Physical AI'})[slug]}</span><span aria-hidden="true">→</span></a>)}</div></section>
 </>;
}
